apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: voting-demo
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: voting-demo
    spec:
      containers:
        - name: result-app-pod
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
