apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-demo
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-demo
    spec:
      containers:
        - name: worker-app-pod
          image: dockersamples/examplevotingapp_worker
