apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-demo
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
