apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-demo
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-demo
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          ports:
            - containerPort: 5432
