apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: voting-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: voting-demo
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: voting-demo
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
